---
stages:
  - validate
  - test
  - build
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
sast:
  stage: test

.pnpm:
  image: node:20
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir /tmp/.pnpm-store
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - /tmp/.pnpm-store

lint:
  stage: validate
  extends: .pnpm
  script:
    - pnpm install --shamefully-hoist || pnpm install --shamefully-hoist --force
    - pnpm lint

build:
  stage: build
  extends: .pnpm
  script:
    - pnpm install --shamefully-hoist || pnpm install --shamefully-hoist --force
    - pnpm build
    - mv dist "./${CI_PROJECT_NAME}"
    - tar -czf "${CI_PROJECT_NAME}.tar.gz" "./${CI_PROJECT_NAME}"
